### PR TITLE
update go.mod - to add easy logging for dex-server

### PR DESCRIPTION
**Pull request by leena-jawale**
Signed-off-by: Leena Jawale <ljawale@redhat.com>

Updated go.mod dex-operator dependency to add easy logging for dex-server pod

### CODE REVIEW

**Review by robinbobbitt — CHANGES_REQUESTED** [review]
@leena-jawale we need to update https://github.com/identitatem/idp-mgmt-operator/blob/main/config/installer/installer.yaml#L52 as documented in the README. Thanks!

**Comment by chrisahl** [comment]
/test e2e-cluster

Rerun to see if we get the same error

**Pull request merged**
