### PR TITLE
Rename placementdecision methods

### PR DESCRIPTION
**Pull request by itdove**
Signed-off-by: Dominique Vernier <dvernier@redhat.com>

### CODE REVIEW

**Comment by chrisahl** [comment]
Only concern I have is around the Dockerfile change for `GOSUMDB=off`.  Is this something that we will leave in permanently?  And if so, are there any negative side effects?

**Comment by itdove** [comment]
@chrisahl `GOSUMDB=off.` is the only solution we found for the time being. it seems the checksum can not be found (strange enough it works on my laptop). We can try to remove it in a next PR to see if it works again (maybe a temporary issue).
Yes it can have a negative effect as we can not verify the downloaded checksum but I guess if the file is corrupted then other tests will fail.

**Pull request merged**
