### PR TITLE
wire in ginkgo e2e tests

### PR DESCRIPTION
**Pull request by chrisahl**
Signed-off-by: Chris Ahl <cahl@redhat.com>

### CODE REVIEW

**Review by vidyanambiar — COMMENTED** [review]
Looks great, @chrisahl!

Does the test report show up in the logs? I clicked on `Details` next to `ci/prow/e2e-cluster ` in the PR check and I see it passed but can't view ginkgo related logs. Is that expected?

**Comment by chrisahl** [comment]
@vidyanambiar  So if the tests pass, only a minimum of data is shown and you have to go to the top right of the page and select Artifacts.  Then you can navigate to artifacts > e2e-cluster > e2e-test > build-log.txt

**Review by vidyanambiar — APPROVED** [review]
/lgtm

**Pull request merged**
