### PR TITLE
Precommit hook

### PR DESCRIPTION
**Pull request by leena-jawale**
/hold

issue: https://github.com/stolostron/backlog/issues/19778

### CODE REVIEW

**Review by chrisahl — COMMENTED** [review]
So I think I am good with this and it should work when we need to update previous version/replaces.   Just need to remember to do it.  I should probably add/update a section in our Development Notes doc

**Review by robinbobbitt — APPROVED** [review]
This looks good to me. In a future iteration, we should try to update `make bundle` such that all places that need the version number are updated from the CATALOG_IMAGE_VERSION file, so changing the version consists of updating CATALOG_IMAGE_VERSION and running make bundle rather than updating a number of files. Thanks @leena-jawale !

**Comment by robinbobbitt** [comment]
@leena-jawale @chrisahl we should probably rename CATALOG_IMAGE_VERSION to PREVIOUS_CATALOG_IMAGE_VERSION  in a future PR for clarity.

**Pull request merged**
